<?php

	$navAdmin = array( // directory => array of pages (index for root)
		'tables' => array( // file => label
			'index'				=> t('Setup'),
			
			'gfalist'			=> t('GFA List'),
		),
	);

?>


<!-- left nav admin navigation -->
<?php


if(! $this->hasACL ('facility_and_person_approver') ) {
	unset( $navAdmin['people']['new-people'] ); // remove approval page links if no ACL of approver
	unset( $navAdmin['facilities']['new-facilities'] );
} else if ( ! $this->setting['module_person_approval'] ) {
	unset( $navAdmin['people']['new-people'] );
} else if ( ! $this->setting['module_facility_approval'] ){
	unset( $navAdmin['facilities']['new-facilities'] );
} else {
	$db = Zend_Db_Table_Abstract::getDefaultAdapter (); // highlight links if theres work here to do for the approver
	$areUnapproved = $db->fetchCol('select 1 from person where approved is null');
	if($areUnapproved)
		$navAdmin['people']['new-people'] .= ' <b>*'.t('New').'*</b>';
	$areUnapprovedFac = $db->fetchCol('select 1 from facility where approved is null');
	if($areUnapprovedFac)
		$navAdmin['facilities']['new-facilities'] .= ' <b>*'.t('New').'*</b>';
}


// Note: $path defined in header.phtml

// Get page title and next page
$parsed_url = parse_url(Settings::$COUNTRY_BASE_URL);
$pathFront = @$parsed_url['path'];
if ( $pathFront )
$path = str_replace($pathFront,'',$_SERVER['REQUEST_URI']);
else
$path = $_SERVER['REQUEST_URI'];
$path = $_SERVER['REQUEST_URI'];

// Strip off URL params if any (will be when debugging in Eclipse)
//$qmarkpos = strpos($path, "?");
//if ($qmarkpos != false) {
//	$path = substr($path, 0, $qmarkpos);
//}

$path = explode('/',$path);

//$path = $_SERVER['REQUEST_URI'];
$page = explode('-',$path[2]);
$page[1] = implode('-', array_slice($page,1)); // allow hyphens



//$page = 'assign-title';
$pageTitle = "";
$nextUri = "";
if(isset($page[1]) && isset($navAdmin[$page[0]][$page[1]])) {
	$pageTitle = $navAdmin[$page[0]][$page[1]];

	// get next array element
	foreach($navAdmin as $dir => $navRay) {
		foreach($navRay as $key => $val) {

			if($dir == $page[0] && $key == $page[1]) {
				$next = next($navRay);
				$rayDir = $dir;
				if(!$next) { // end of array, get next array
					$navRay = current($navAdmin);
					$rayDir = key($navAdmin);
					$next = next($navRay); // skip first element (index)

				}
				$nextUri = $rayDir."-".key($navRay);
				break;
			}
			next($navRay);
		}

	}
}
$sections = array();
$labels = array();

// generate admin navigation
foreach($navAdmin as $dir => $navRay) {


	foreach($navRay as $file => $label) {

		if($dir == 'index' || $file == 'index') {
			$uri = false;
		} else {
			$uri = "$dir-$file";
		}

		if ( !isset($sections[$dir]) ) $sections[$dir] = array();

		if($uri) {
			$isActive = ($path[2] == $uri) ? ' class="active"' : '';
			$sections[$dir][] =	'<li'.$isActive.'><a href="'.($this->base_url).'/admin/'.$uri.'" '.$isActive.'>'.$label."</a>".'</li>';
		} else {
			$labels[$dir] =	$label;
		}

	}

}

echo '<ul>';
foreach($sections as $dir => $s) {
	echo '<li>'.$labels[$dir]."\n".'<ul>'.implode("\n", $s).'</ul>'."\n".'</li>';
}
echo '</ul>';


?>
