<script language="javascript">

function adminChecks(val) {
	chked = null;
	if( val==1 )
		chked = 'checked';
	$('#admin_box input[type="checkbox"]').attr('checked', chked);
	event.preventDefault();
	return false;
}

function showAdminLevels() {
	$('#admin_box').toggle();
	if(!$('#toggle').is(':checked')){
		$('#admin_box input').removeAttr('checked');
	}
}

//TA:#415
function setOrgAccessStatus() { /* organizer logic (restrict access), show hide, uncheck and check */
	if ($('#acl_org_restrict').attr('checked') == 'checked') {
		$('#orgs').slideDown();	
		if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
			 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
			 for(var i = 0; i < mechFields.length; i++) {
				 $(mechFields[i]).parent().parent().parent().hide();
				 orginizer_selected(mechFields[i]);
			 }
		}
	}else {
		$('#orgs').slideUp();
		if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
		 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
		 for(var i = 0; i < mechFields.length; i++) {
			    $(mechFields[i]).parent().parent().parent().show();
		 }
		 var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
			for(var i = 0; i < orgFields.length; i++) {
				$(orgFields[i]).attr('checked', false);
			}
		}
	}

	var edCourseRB = YAHOO.util.Dom.get("edit_course");
	var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
	for(var i = 0; i < orgFields.length; i++) {
		var isDisabled = false;
		if (edCourseRB.checked == false) isDisabled = true;
		orgFields[i].disabled = isDisabled;
		orginizer_selected(orgFields[i]);//TA:#415.2
	}
	
}

//TA:#415
function setMechanismAccessStatus(){
	if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
		$('#mechanisms').slideDown();
	}
	else {
		$('#mechanisms').slideUp();
	}

	var edCourseRB = YAHOO.util.Dom.get("edit_course");
	var orgFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
	for(var i = 0; i < orgFields.length; i++) {
		var isDisabled = false;
		if (edCourseRB.checked == false) isDisabled = true;
		orgFields[i].disabled = isDisabled;
	}
// 	var allOrgsRB = YAHOO.util.Dom.get("mechanism_option_all");
// 	if ( allOrgsRB.checked &&  edCourseRB.checked ) {
// 		for(var i = 0; i < orgFields.length; i++) {
// 			orgFields[i].checked = true;
// 			orgFields[i].disabled = true;
// 		}
// 		allOrgsRB.disabled = false;
// 	} else if ( edCourseRB.checked ) {
// 		for(var i = 0; i < orgFields.length; i++) {
// 			orgFields[i].disabled = false;
// 		}
// 	}
}

//TA:#415.2
var orginizer_selected = function (elem) {
	var org_id = $(elem).attr('id').replace("training_organizer_option_", "");    
	var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
	for(var i = 0; i < mech_fields.length; i++) {
		if($(mech_fields[i]).parent().parent().parent().attr('id') == org_id){
			if($(elem).attr('checked')){
			  $(mech_fields[i]).parent().parent().parent().show();
			}else{
				$(mech_fields[i]).parent().parent().parent().hide();
				$(mech_fields[i]).attr('checked', false);
			}
		}
	}				
}

YAHOO.util.Event.onDOMReady(setOrgAccessStatus);
YAHOO.util.Event.onDOMReady(setMechanismAccessStatus);//TA:#415

</script>

<form action="" id="userForm" method="POST">
	<div class="fieldLabel" id="first_name_lbl"><span class="required">*</span><?php echo $this->translation['First Name'];?></div>
	<div class="fieldInput"><input type="text" name="first_name" size="32" maxlength="32" value="<?php echo $this->user['first_name'];?>"/></div>
	<div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
	<div class="fieldInput"><input type="text" name="last_name" size="32" maxlength="32" value="<?php echo $this->user['last_name'];?>"/></div>
	<div class="fieldLabel"  id="username_lbl"><span class="required">*</span><?php tp('Login');?></div>
	<div class="fieldInput"><input type="text" name="username" size="32" maxlength="32" value="<?php echo $this->user['username'];?>"/></div>
	<div class="fieldLabel"  id="password_lbl"><span class="required">*</span><?php tp('Password');?></div>
	<div class="fieldInput"><input type="text" name="password" size="32" maxlength="32" value="<?php echo $this->user['password'];?>"/></div>
	<div class="fieldLabel"  id="email_lbl"><span class="required">*</span><?php tp('E-mail');?></div>
	<div class="fieldInput"><input type="text" name="email" size="32" maxlength="256" value="<?php echo $this->user['email'];?>"/></div>
	<div class="clear"></div>



	<div class="fieldLabelThin" for="spacer"></div>
	<div class="fieldInput"><input type="checkbox" id="send_email" name="send_email"  CHECKED /><label for="send_email"> <?php tp('Send email with login information');?></label></div>
	<div class="fieldLabelThin" for="spacer"></div>
	<input type="submit" value="<?php tp('Next User');?>" title="save and continue" class="submitArrow"/>
	<div style="float:right;">&nbsp;</div>
	<button type="button" id="Finished" title="save this record" class="submitNoArrow" /><?php tp('Finished');?></button>
	<div class="clear"></div>

</form>
<script type="text/javascript">
addAjaxSubmit('Finished','userForm','<?php echo $this->base_url;?>/user/add/outputType/json');

$(document).ready(function () {
	$('#orgcheckall').click(function (e) {   /* check all btn  */
		e.preventDefault();
		$('#orgs input[name="training_organizer_option_id[]"]').attr('checked', 'checked');
		//TA:#415
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
			$(mech_fields[i]).parent().parent().parent().show();
		}			
	});
	$('#orguncheckall').click(function (e) { /* check none btn */
		e.preventDefault();
		$('#training_organizer_option_all,#orgs input[name="training_organizer_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
		//TA:#415
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
				$(mech_fields[i]).parent().parent().parent().hide();
				$(mech_fields[i]).attr('checked', false);
		}
	});

	//TA:#415
	$('#mechanismcheckall').click(function (e) {   /* check all btn  */
		e.preventDefault();
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
			if($(mech_fields[i]).is(':hidden')){
				mech_fields[i].checked = false;
			}else{
				mech_fields[i].checked = true;
			}
		}
	});
	$('#mechanismuncheckall').click(function (e) { /* check none btn */
		e.preventDefault();
		$('#mechanism_option_all,#mechanisms input[name="mechanism_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
	});
	///

	$('#edit_country_options').click(function (e) { /* edit country options checkbox (this is master admin) */
		$('#admin_box input[type="checkbox"]').attr('checked', $(this).is(':checked'));
	});

	$('#admin_select_all').click(function (e) {
		e.preventDefault();
		adminChecks(1);
	});
	$('#admin_select_none').click(function (e) {
		e.preventDefault();
		adminChecks(0);
	});

	//TA:#421
	if($('#employees_module').attr('checked')){
		$("#position_access").prop('disabled',false);
	}else{
		 $("#position_access").prop('disabled',true);
	}
	$('#employees_module').click(function (e) {
		if($('#employees_module').attr('checked')){
			$("#position_access").prop('disabled',false);
		}else{
			 $("#position_access").prop('disabled',true);
			 $("#position_access").prop('checked',false);
		}
	})	
	///
});

function toggleinstitution(sender){
	if (sender.checked){
		$(".institutioncheck").prop('checked',true);
		$(".institutioncheck").prop('disabled',true);
	} else {
		$(".institutioncheck").prop('disabled',false);
	}
}
</script>
<div class="clear"></div>