<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->translation['Application Name'];?> | <?php tp('Edit Account');?></title>
		<?php
			require_once('views/helpers/ScriptContainer.php');
			print ScriptContainer::$instance->renderCSSHead();
			print ScriptContainer::$instance->renderJSHead();
		?>
	</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">
			<h1><?php tp('Edit Account');?></h1>
			<div class="clear"></div>
			<form action="" id="userForm" method="post">
				<div class="fieldLabel" id="first_name_lbl">
					<span class="required">*</span><?php echo $this->translation['First Name'];?></div>
				<div class="fieldInput">
					<input type="text" name="first_name" size="32" maxlength="32"
						value="<?php echo $this->user['first_name'];?>" />
				</div>
				<div class="fieldLabel" id="last_name_lbl">
					<span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
				<div class="fieldInput">
					<input type="text" name="last_name" size="32" maxlength="32"
						value="<?php echo $this->user['last_name'];?>" />
				</div>
				<div class="fieldLabel" id="username_lbl">
					<span class="required">*</span><?php tp('Login');?></div>
				<div class="fieldInput">
					<input type="text" name="username" size="32" maxlength="32"
						value="<?php echo $this->user['username'];?>" />
				</div>
				<div class="fieldLabel" id="email_lbl">
					<span class="required">*</span><?php tp('E-mail');?></div>
				<div class="fieldInput">
					<input type="text" name="email" size="32" maxlength="255"
						value="<?php echo $this->user['email'];?>" />
				</div>
				<div class="fieldLabel" id="password_lbl"> <?php tp('New password');?></div>
				<div class="fieldInput">
					<input type="password" name="password" size="32" maxlength="32"
						autocomplete="false" autocomplete='off' value="" />
				</div>
				<div class="fieldLabel" id="confirm_password_lbl"> <?php tp('Confirm new password');?></div>
				<div class="fieldInput">
					<input type="password" name="confirm_password" size="32"
						maxlength="32" autocomplete='off' value="" />
				</div>
				<div class="clear"></div>


					<?php if ( !$this->user['is_blocked'] ) { ?>
					<div style="margin-left: 2em;">
					<a href="" onclick="doDelete(); return false;"> <?php tp('Block this User');?></a>
				</div>
				<script language="JavaScript">
						function doDelete() {
							if(confirm("<?php tp('Are you sure you wish to block this user?');?>")) {
								window.location = '<?php echo $this->base_url;?>/user/delete/id/<?php echo $this->user['id'];?>';
								return false;
							}
						}
					</script>
					<?php } else { ?>
					<div style="margin-left: 2em;">
					This user is currently blocked. <a href=""
						onclick="doActivate(); return false;"> <?php tp('Activate this User');?></a>
				</div>
				<script language="JavaScript">
						function doActivate() {
							if(confirm("<?php tp('Are you sure you wish to activate this user?');?>")) {
								window.location = '<?php echo $this->base_url;?>/user/activate/id/<?php echo $this->user['id'];?>';
								return false;
							}
						}
					</script>
					<?php } ?>
					<button type="button" id="Finished" title="save this record"
					class="submitNoArrow" /><?php tp('Save changes');?></button>
				<div class="clear"></div>


			</form>
			<div class="clear"></div>
			<script type="text/javascript">
					addAjaxSubmit('Finished','userForm','<?php echo $this->base_url;?>/user/edit/id/<?php echo $this->user['id'];?>/outputType/json');
				</script>

		</div>
		<div id="footer"> <?php require_once('views/scripts/footer.phtml');?></div>


	</div>

	<script language="javascript">


	$(document).ready(function () {
		$('#orgcheckall').click(function (e) {   /* check all btn  */
			e.preventDefault();
			$('#orgs input[name="training_organizer_option_id[]"]').attr('checked', 'checked');
			//TA:#415
			var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
			for(var i = 0; i < mech_fields.length; i++) {
				$(mech_fields[i]).parent().parent().parent().show();
			}			
		});
		$('#orguncheckall').click(function (e) { /* check none btn */
			e.preventDefault();
			$('#training_organizer_option_all,#orgs input[name="training_organizer_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
			//TA:#415
			var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
			for(var i = 0; i < mech_fields.length; i++) {
 				$(mech_fields[i]).parent().parent().parent().hide();
 				$(mech_fields[i]).attr('checked', false);
			}
		});

		//TA:#415
		$('#mechanismcheckall').click(function (e) {   /* check all btn  */
			e.preventDefault();
			var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
			for(var i = 0; i < mech_fields.length; i++) {
				if($(mech_fields[i]).is(':hidden')){
					mech_fields[i].checked = false;
				}else{
					mech_fields[i].checked = true;
				}
			}
		});
		$('#mechanismuncheckall').click(function (e) { /* check none btn */
			e.preventDefault();
			$('#mechanism_option_all,#mechanisms input[name="mechanism_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
		});
		///

		$('#edit_country_options').click(function (e) { /* edit country options checkbox (this is master admin) */
			$('#admin_box input[type="checkbox"]').attr('checked', $(this).is(':checked'));
		});

		$('#admin_select_all').click(function (e) {
			e.preventDefault();
			adminChecks(1);
		});
		$('#admin_select_none').click(function (e) {
			e.preventDefault();
			adminChecks(0);
		})

		//TA:#421
		if($('#employees_module').attr('checked')){
			$("#position_access").prop('disabled',false);
		}else{
			 $("#position_access").prop('disabled',true);
		}
		$('#employees_module').click(function (e) {
			if($('#employees_module').attr('checked')){
				$("#position_access").prop('disabled',false);
			}else{
				 $("#position_access").prop('disabled',true);
				 $("#position_access").prop('checked',false);
			}
		})	
		///
		
	});

	function adminChecks(val) { /* check all admin options btn */
		chked = null;
		if( val==1 )
			chked = 'checked';
		$('#admin_box input[type="checkbox"]').attr('checked', chked);
		return false;
	}

	function showAdminLevels() { /* show hide #admin_box btn */
		$('#admin_box').toggle();
		if(!$('#toggle').is(':checked')){
			$('#admin_box input').removeAttr('checked');
		}
	}

	//TA:#415
	function setOrgAccessStatus() { /* organizer logic (restrict access), show hide, uncheck and check */
		if ($('#acl_org_restrict').attr('checked') == 'checked') {
			$('#orgs').slideDown();	
			if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
				 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
				 for(var i = 0; i < mechFields.length; i++) {
					 $(mechFields[i]).parent().parent().parent().hide();
					 orginizer_selected(mechFields[i]);
				 }
			}
		}else {
			$('#orgs').slideUp();
			if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
			 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
			 for(var i = 0; i < mechFields.length; i++) {
				    $(mechFields[i]).parent().parent().parent().show();
			 }
			 var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
				for(var i = 0; i < orgFields.length; i++) {
					$(orgFields[i]).attr('checked', false);
				}
			}
		}

		var edCourseRB = YAHOO.util.Dom.get("edit_course");
		var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
		for(var i = 0; i < orgFields.length; i++) {
			var isDisabled = false;
			if (edCourseRB.checked == false) isDisabled = true;
			orgFields[i].disabled = isDisabled;
			orginizer_selected(orgFields[i]);//TA:#415.2
		}
		
	}

	//TA:#415
	function setMechanismAccessStatus(){
		if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
			$('#mechanisms').slideDown();
		}else {
			$('#mechanisms').slideUp();
		}

		var edCourseRB = YAHOO.util.Dom.get("edit_course");
		var orgFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
		for(var i = 0; i < orgFields.length; i++) {
			var isDisabled = false;
			if (edCourseRB.checked == false) isDisabled = true;
			orgFields[i].disabled = isDisabled;
		}
	}

	//TA:#415.2
	var orginizer_selected = function (elem) {
		var org_id = $(elem).attr('id').replace("training_organizer_option_", "");    
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
			if($(mech_fields[i]).parent().parent().parent().attr('id') == org_id){
				if($(elem).attr('checked')){
				  $(mech_fields[i]).parent().parent().parent().show();
				}else{
					$(mech_fields[i]).parent().parent().parent().hide();
					$(mech_fields[i]).attr('checked', false);
				}
			}
		}				
	}

	$(document).ready(setOrgAccessStatus);
	$(document).ready(setMechanismAccessStatus);//TA:#415


	<?php
		$showAdmin = false; // docready - show #admin_box if user has admin acls
		foreach ($this->user['acls'] as $key => $value) {
			if(strpos($value, 'acl_editor_') !== false){
				$showAdmin = true;
				break;
			}
		}

		if( in_array('edit_country_options',$this->user['acls'])  ) $showAdmin = true;
		if( in_array('add_edit_users',      $this->user['acls'])  ) $showAdmin = true;
		if( in_array('acl_admin_training',  $this->user['acls'])  ) $showAdmin = true;
		if( in_array('acl_admin_people',    $this->user['acls'])  ) $showAdmin = true;
		if( in_array('acl_admin_facilities',$this->user['acls'])  ) $showAdmin = true;

		if ($showAdmin) { // add docready javascript
			echo '$(document).ready(function () {
				$("#toggle").attr("checked", "checked");
				$("#admin_box").show();
			});';
		}

	?>


	function toggleinstitution(sender){
		if (sender.checked){
			$(".institutioncheck").prop('checked',true);
			$(".institutioncheck").prop('disabled',true);
		} else {
			$(".institutioncheck").prop('disabled',false);
		}
	}

    function toggleprogram(sender){
        if (sender.checked){
            $(".programcheck").prop('checked',true);
            $(".programcheck").prop('disabled',true);
        } else {
            $(".programcheck").prop('disabled',false);
        }
	}


	//TA:10 added 8/11/2014
	function preserviceACL(){
	if ($('#pre_service').attr('checked') == 'checked')
		$('#ps_acl').slideDown();
	else
		$('#ps_acl').slideUp();
	
}

</script>

	<div class="clear"></div>

</body>
</html>

