<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Activity Detail');?> <?php echo ($this->mode != 'search'? t('Reports'):t('Search') );  ?></title>
<?php

require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');
if ( $this->mode == 'count' )
	$checkLabel = t('group');
$checkVisible = '';
if ($this->mode == 'search' ) {
	$checkVisible = ' style="display:none;" ';
}
?>

<script  type="text/javascript">
	function gotoPage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>

</head>
<body class="yui-skin-sam" >
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Activity Detail ' . ($this->mode != 'search'? 'Reports':'Search' ) )?></h1>
 <?php if ($this->mode != 'search' ) { ?>
    	<div class="fieldLabel"><?php tp('Select activity detail report');?></div>
    	<select id="activity_detail" name="activity_detail" onchange="gotoPage('activity_detail');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/activity-detail-by-project-code" <?php if ($this->mode == 'id') echo 'selected="selected"';?>><?php echo t('Activity Detail by Project Code');?></option>
    		<option value="/reports/activity-detail-by-gfa" <?php if ($this->mode == 'count') echo 'selected="selected"';?>><?php echo t('Activity Detail by GFA');?></option>
   	</select>
   <?php } ?>
   <br clear="all" />
	   <form action="" method="get">
   <fieldset <?php if( $this->mode != 'search') echo 'id="criteria"'; ?> ><legend><?php tp('Select Criteria');?></legend>
  <div id="dividers">
    <div class="fieldLabel " ></div>
    <div class="fieldInput criteria-header"><div  class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>


<div id="gfaAutoComplete">
	    <div class="fieldLabel" id="gfaInput_lbl"><?php tp('GFA');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox"  disabled="disabled" name="showGFA" checked /></div>
	    <div  class="leftBorder"><select id="gfaInput" name="gfaInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->gfa as $vals ) {
		
		//file_put_contents('/vagrant/vagrant/logs/php_debug.log', 'activity-detail: >' . PHP_EOL, FILE_APPEND | LOCK_EX); ob_start();
		//var_dump("vals:", $vals, "END");
        //$toss = ob_get_clean(); file_put_contents('/vagrant/vagrant/logs/php_debug.log', $toss . PHP_EOL, FILE_APPEND | LOCK_EX);
        
			echo '<option value="'.$vals['GFA'].'" '.($this->criteria['gfaInput'] == $vals['id']?'':'').'>'.$vals['GFA'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>
	
	<div id="budgetNbrAutoComplete">
	    <div class="fieldLabel" id="budgetNbrInput_lbl"><?php tp('Budget Number');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox"  disabled="disabled" name="showBudgetNbr" checked /></div>
	    <div  class="leftBorder"><select id="budgetNbrInput" name="budgetNbrInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->budgetNbr as $vals ) {
			echo '<option value="'.$vals['BudgetNbr'].'" '.($this->criteria['budgetNbrInput'] == $vals['id']?'':'').'>'.$vals['BudgetNbr'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>




</div>
	<div class="clear"></div><br/><br/>
	
	
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp("Day");?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp("Month");?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp("Year");?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	//makeCalendar("startdate","start-day", "start-month", "start-year");
		    	<?php //TA:#350
                        $locale = ITechTranslate::getLocale();
                        if ( $locale !== null && $locale == 'uk_UK.UTF-8'){ ?>
                             makeCalendarUkraine("startdate", "start-day", "start-month", "start-year", null, "calendarpicker", "buttoncalendar1");
                        <?php }else{?>
                             makeCalendarDefault("startdate", "start-day", "start-month", "start-year", null, "calendarpicker", "buttoncalendar1");
                        <?php }?>
		    });
		</script>
	</div>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp("Day");?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp("Month");?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp("Year");?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	//makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    	<?php //TA:#350
                        $locale = ITechTranslate::getLocale();
                        if ( $locale !== null && $locale == 'uk_UK.UTF-8'){ ?>
                            makeCalendarUkraine("enddate", "end-day", "end-month", "end-year", null, "calendarpicker2","buttoncalendar2");
                        <?php }else{?>
                            makeCalendarDefault("enddate", "end-day", "end-month", "end-year", null, "calendarpicker2","buttoncalendar2");
                        <?php }?>
		    });
		</script>
	</div>


	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
   
   
   
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
<!-- TA:80 print only trainings part -->
    <div class="fieldIndentNoMargin"><?php echo t('Trainings matched with Facilities');?> <span class="total"><?php echo $this->count;?> <?php if ( $this->mode == 'count' ) echo t('Participants'); else echo '';?></span><?php echo $this->printAndExport("trainings");?></div>
<?php } ?>
    <div id="trainings" class="itechTable"></div>
    <script type="text/javascript">
    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/training/view/id/" + oRecord.getData("id") + oRecord.getData("GFA") + oRecord.getData("BudgetNbr") +"'>" + sData + "</a>";
	        };

	        var trainingData = [
<?php $isFirstRow = true;
$cnt = 0;
foreach($this->results as $row) {
	if ( (!$_REQUEST['limit'])  or ($cnt < 100) ) {
		if (!$isFirstRow )
			echo ',';
		$isFirstRow = false;
		echo '['. $row['id'];
		if ( isset($row['id']) )
			echo ',"'.$row['GFA'].'"';
			echo ',"'.$row['BudgetNbr'].'"';
		if ( $this->criteria['showFacility'] )
			echo ',"'.$row['facility_name'].'"';
		if ( $this->criteria['showType'] )
			echo ',"'.$row['facility_type_phrase'].'"';
		if ( $this->criteria['showSponsor'] )
			echo ',"'.$row['facility_sponsor_phrase'].'"';
		if ( $this->criteria['showProvince'] )
			echo ',"'.$row['province_name'].'"';
		if ( $this->criteria['showDistrict'] )
			echo ',"'.$row['district_name'].'"';
    if ( $this->criteria['showRegionC'] )
      echo ',"'.$row['region_c_name'].'"';
	    if ( $this->criteria['showRegionD'] )
    		echo ',"'.$row['region_d_name'].'"';
	    if ( $this->criteria['showRegionE'] )
    		echo ',"'.$row['region_e_name'].'"';
	    if ( $this->criteria['showRegionF'] )
    		echo ',"'.$row['region_f_name'].'"';
	    if ( $this->criteria['showRegionG'] )
    		echo ',"'.$row['region_g_name'].'"';
	    if ( $this->criteria['showRegionH'] )
    		echo ',"'.$row['region_h_name'].'"';
	    if ( $this->criteria['showRegionI'] )
    		echo ',"'.$row['region_i_name'].'"';
			if ( $this->criteria['showTrainingTitle'] or ($this->mode == 'search' ))
			echo ',"'.$row['training_title'].'"';
		if ( $this->criteria['showLocation'] )
			echo ',"'.$row['training_location_name'].'"';
		if ( $this->criteria['showOrganizer'] )
			echo ',"'.$row['training_organizer_phrase'].'"';
		if ( $this->criteria['showLevel'] )
			echo ',"'.$row['training_level_phrase'].'"';
		if ( $this->criteria['showTopic'] )
			echo ',"'.$row['training_topic_phrase'].'"';
		if ( $this->criteria['showPepfar'] )
			echo ',"'.$row['pepfar_category_phrase'].'"';
		if ( $this->criteria['showTot'] )
			echo ',"'.$row['is_tot'].'"';
		if ( $this->criteria['showGender'] )
			echo ',"'.$row['gender'].'"';
		if ( $this->criteria['showAge'] )
			echo ','.$row['age']    ;
		if ( $this->criteria['showQual'] )
			echo ',"'.$row['qualification_phrase'].'"';
		echo "]";
		$cnt++;
}}
   ?>];

var trainingColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "Count", sortable:true, resizeable:true}
<?php } else { ?>
{key:"id", label: "<?php tp('ID')?>", sortable:true, resizeable:true, formatter: formatViewUrl},
<!-- {key:"GFA", label: "<?php tp('GFA');?>", sortable:true, resizeable:true} -->
<!-- key:"BudgetNbr", label: "<?php tp('BudgetNbr');?>", sortable:true, resizeable:true} -->
<?php } ?>
<?php if ( 1 ) { ?>
	{key:"GFA", label: "<?php tp('GFA');?>", sortable:true, resizeable:true}
<?php } ?>
<?php if ( 1 ) { ?>
	,{key:"BudgetNbr", label: "<?php tp('BudgetNbr');?>", sortable:true, resizeable:true}
<?php } ?>


<?php if ( $this->criteria['showGFA'] ) { ?>
   ,{key:"GFA", label: "<?php tp('GFA');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showBudgetNbr'] ) { ?>
   ,{key:"BudgetNbr", label: "<?php tp('BudgetNbr');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showSponsor'] ) { ?>
   ,{key:"facility_sponsor_phrase", label: "<?php tp('Facility Sponsor');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showProvince'] ) { ?>
   ,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showDistrict'] ) { ?>
   ,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionC'] ) { ?>
   ,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionD'] ) { ?>
   ,{key:"region_d_name", label: "<?php echo (@$this->translation['Region D']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionE'] ) { ?>
   ,{key:"region_e_name", label: "<?php echo (@$this->translation['Region E']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionF'] ) { ?>
   ,{key:"region_f_name", label: "<?php echo (@$this->translation['Region F']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionG'] ) { ?>
   ,{key:"region_g_name", label: "<?php echo (@$this->translation['Region G']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionH'] ) { ?>
   ,{key:"region_h_name", label: "<?php echo (@$this->translation['Region H']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionI'] ) { ?>
   ,{key:"region_i_name", label: "<?php echo (@$this->translation['Region I']); ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showTrainingTitle']  or ($this->mode == 'search' )) { ?>
   ,{key:"training_title", label: "<?php echo (@$this->translation['Training Name']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showLocation'] ) { ?>
   ,{key:"training_location_name", label: "<?php echo t('Training Location');?>", sortable:true, resizeable:true} //TA:66 translation
 <?php } ?>
<?php if ( $this->criteria['showOrganizer'] ) { ?>
   ,{key:"training_organizer_phrase", label: "<?php echo (@$this->translation['Training Organizer']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showLevel'] ) { ?>
   ,{key:"training_level_phrase", label: "<?php echo (@$this->translation['Training Level']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTopic'] ) { ?>
   ,{key:"training_topic_phrase", label: "<?php echo (@$this->translation['Training Topic']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPepfar'] ) { ?>
   ,{key:"pepfar_category_phrase", label: "<?php tp('PEPFAR');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTot'] ) { ?>
   ,{key:"is_tot", label: "<?php echo tp('TOT'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showGender'] ) { ?>
   ,{key:"gender", label: "<?php echo (@$this->translation['Gender']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showAge'] ) { ?>
   ,{key:"age", label: "<?php echo tp('Age'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQual'] ) { ?>
   ,{key:"qualification_phrase", label: "<?php echo tp('Qualification'); ?>", sortable:true, resizeable:true}
 <?php } ?>
];






	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
</script>
<?php if ($cnt < count($this->results)) { ?>
<div  class="fieldIndentNoMargin">[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a></div>
<?php } ?>
  </div>
   <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>
