<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Activity Detail');?> <?php echo ($this->mode != 'search'? t('Reports'):t('Search') );  ?></title>
<?php

require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');
if ( $this->mode == 'count' )
	$checkLabel = t('group');
$checkVisible = '';
if ($this->mode == 'search' ) {
	$checkVisible = ' style="display:none;" ';
}
?>

<script  type="text/javascript">
	function gotoPage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>

</head>
<body class="yui-skin-sam" >
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Activity Detail ' . ($this->mode != 'search'? 'Reports':'Search' ) )?></h1>
 <?php if ($this->mode != 'search' ) { ?>
    	<div class="fieldLabel"><?php tp('Select activity detail report');?></div>
    	<select id="activity_detail" name="activity_detail" onchange="gotoPage('activity_detail');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/bars" <?php echo 'selected="selected"';?>><?php echo t('BARS');?></option>
    		<option value="/reports/activity-detail"><?php echo t('Activity Detail');?></option>
   	</select>
   <?php } ?>
   <br clear="all" />
	   <form action="" method="get">
   <fieldset <?php if( $this->mode != 'search') echo 'id="criteria"'; ?> ><legend><?php tp('Select Criteria');?></legend>
  <div id="dividers">
    <div class="fieldLabel " ></div>
    <div class="fieldInput criteria-header"><div  class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>


	
	<div id="budgetNbrAutoComplete">
	    <div class="fieldLabel" id="budgetNbrInput_lbl"><?php tp('Budget Number');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox"  disabled="disabled" name="showBudgetNbr" checked /></div>
	    <div  class="leftBorder"><select id="budgetNbrInput" name="budgetNbrInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->budgetNbr as $vals ) {
			echo '<option value="'.$vals['BudgetNbr'].'" '.($this->criteria['budgetNbrInput'] == $vals['id']?'':'').'>'.$vals['BudgetNbr'].'</option>';
	}
	?>
</select>
	    </div></div>
	 </div>

	<div id="budgetName">
	    <div class="fieldLabel" id="budgetNameInput_lbl"><?php tp('Budget Name');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showBudgetName" checked /></div>
	    <div  class="leftBorder"><select id="budgetNameInput" name="budgetNameInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->budgetName as $vals ) {
			echo '<option value="'.$vals['BudgetName'].'" '.($this->criteria['budgetNameInput'] == $vals['id']?'':'').'>'.$vals['BudgetName'].'</option>';
	}
	?>
</select>
	  	</div></div>
	 </div>
			<div id="fiscalmonth">
	    <div class="fieldLabel" id="modifiedInput_lbl"><?php tp('Month');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showFiscalMonth" checked /></div>
	    <div  class="leftBorder"><select id="fiscalmonthInput" name="fiscalmonthInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->fiscalmonth as $vals ) {
			echo '<option value="'.$vals['FiscalMonth'].'" '.($this->criteria['fiscalmonthInput'] == $vals['id']?'':'').'>'.$vals['FiscalMonth'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>
	
			<div id="fiscalyear">
	    <div class="fieldLabel" id="fiscalyearInput_lbl"><?php tp('Year');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showFiscalYear" checked /></div>
	    <div  class="leftBorder"><select id="fiscalyearInput" name="fiscalyearInput" >
	<option value="" selected="selected">--<?php tp('choose');?>--
	<?php
	    
		foreach ( $this->fiscalyear as $vals ) {
			echo '<option value="'.$vals['FiscalYear'].'" '.($this->criteria['fiscalyearInput'] == $vals['id']?'':'').'>'.$vals['FiscalYear'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>
	
</div>
	<div class="clear"></div><br/><br/>
	
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp("Day");?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp("Month");?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp("Year");?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	//makeCalendar("startdate","start-day", "start-month", "start-year");
		    	<?php //TA:#350
                        $locale = ITechTranslate::getLocale();
                        if ( $locale !== null && $locale == 'uk_UK.UTF-8'){ ?>
                             makeCalendarUkraine("startdate", "start-day", "start-month", "start-year", null, "calendarpicker", "buttoncalendar1");
                        <?php }else{?>
                             makeCalendarDefault("startdate", "start-day", "start-month", "start-year", null, "calendarpicker", "buttoncalendar1");
                        <?php }?>
		    });
		</script>
	</div>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp("Day");?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp("Month");?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp("Year");?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	//makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    	<?php //TA:#350
                        $locale = ITechTranslate::getLocale();
                        if ( $locale !== null && $locale == 'uk_UK.UTF-8'){ ?>
                            makeCalendarUkraine("enddate", "end-day", "end-month", "end-year", null, "calendarpicker2","buttoncalendar2");
                        <?php }else{?>
                            makeCalendarDefault("enddate", "end-day", "end-month", "end-year", null, "calendarpicker2","buttoncalendar2");
                        <?php }?>
		    });
		</script>
	</div>


	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
   
   
   
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
    <div class="fieldIndentNoMargin"><?php echo t('Expenses');?> <span class="total"><?php echo $this->count;?> <?php if ( $this->mode == 'count' ) echo t('Records'); else echo '';?></span><?php echo $this->printAndExport("expenses");?></div>
<?php } ?>
    <div id="expenses" class="itechTable"></div>
    <script type="text/javascript">
    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/fin/edit/id/" + oRecord.getData("id") +"'>" + sData + "</a>";
	        };

	        var expenseData = [
<?php $isFirstRow = true;
$cnt = 0;
$so=0.00; $sa=0.00; $sb=0.00; $total=0.00;
$po=''; $pa=''; $pb = '';
foreach($this->results as $row) {
	if ( (!$_REQUEST['limit'])  or ($cnt < 100) ) {
	
		if (!$isFirstRow ) echo ',';
		$isFirstRow = false;
		
		if(($row['budgetnbr'] !== $pb) && $pb !== '' ){
		  
		  	//sub
			echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$pb.'"';
			echo ',"'.$sb.'"';
			echo "]";
			echo ',';
			
			$sb=0;
		}
		
		$sb=$sb+$row['TranAmount']; 
		
		if(($row['account_code'] !== $pa) && $pa !== '' ){
		  
		  	//sub
			echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$pa.'"';
			echo ',"'.$sa.'"';
			echo "]";
			echo ',';
			
			$sa=0;
		}
		
		$sa=$sa+$row['TranAmount']; 
		
		if(($row['object_code'] !== $po) && $po !== '' ){
		  
		  	//sub
			echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$po.'"';
			echo ',"'.$so.'"';
			echo "]";
			echo ',';
			
			$so=0;
		}
		
		$so=$so+$row['TranAmount']; 
		
		// detail	
		echo '["'.$row['object_code'].'"';
		echo ',"'.$row['account_code'].'"';
		echo ',"'.$row['Date'].'"';
		echo ',"'.$row['Description'].'"';
		echo ',"'.$row['FTE'].'"';
		echo ',"'.$row['JV'].'"';
		echo ',"'.$row['TDPrimaryKey'].'"';
		echo ',"'.$row['BudgetNbr'].'"';
		echo ',"'.$row['ProjectCode'].'"';
		echo ',"'.$row['TranAmount'].'"';
		echo "]";
		
		$total=$total+$row['TranAmount'];
		// set prev
		$po=$row['object_code']; $pa=$row['account_code']; $pb=$row['budgetnbr'];		
		$cnt++;
}}

	echo ',';
	echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$pb.'"';
			echo ',"'.$sb.'"';
			echo "]";
			
	echo ',';
	echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$pa.'"';
			echo ',"'.$sa.'"';
			echo "]";
			
	echo ',';
	echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['Date'].'"';
			echo ',"'.$row['Description'].'"';
			echo ',"'.$row['FTE'].'"';
			echo ',"'.$row['JV'].'"';
			echo ',"'.$row['TDPrimaryKey'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'>>> SUB '.$po.'"';
			echo ',"'.$so.'"';
			echo "]";
			echo ',';
			
	echo '["'.'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.$row['Date'].'"';
			echo ',"'.$row['Description'].'"';
			echo ',"'.$row['FTE'].'"';
			echo ',"'.$row['JV'].'"';
			echo ',"'.$row['TDPrimaryKey'].'"';
			echo ',"'.$row['space'].'"';
			echo ',"'.'TOTAL '.'"';
			echo ',"'.$total.'"';
			echo "]";
			



   ?>];

var expenseColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "Count", sortable:true, resizeable:true}
<?php } else { ?>

<?php } ?>

   {key:"object_code", label: "<?php tp('Object Code');?>", sortable:true, resizeable:true}
   ,{key:"account_code", label: "<?php tp('Account Code');?>", sortable:true, resizeable:true}
   
   ,{key:"Date", label: "<?php tp('Date');?>", sortable:true, resizeable:true}
   ,{key:"Description", label: "<?php tp('Description');?>", sortable:true, resizeable:true}
   ,{key:"FTE", label: "<?php tp('FTE');?>", sortable:true, resizeable:true}
   ,{key:"JV", label: "<?php tp('JV');?>", sortable:true, resizeable:true}
   ,{key:"TDPrimaryKey", label: "<?php tp('TDPrimaryKey');?>", sortable:true, resizeable:true}
   ,{key:"budget_name", label: "<?php tp('Budget');?>", sortable:true, resizeable:true}
   ,{key:"ProjectCode", label: "<?php tp('ProjectCode');?>", sortable:true, resizeable:true}
     
   ,{key:"TranAmount", label: "<?php tp('Amount');?>", sortable:true, resizeable:true}

];

	makeDataTable("expenses", null, expenseData, expenseColumnDefs);
</script>
<?php if ($cnt < count($this->results)) { ?>
<div  class="fieldIndentNoMargin">[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a></div>
<?php } ?>
  </div>
   <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</div>

</body>
</html>
