<?php

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!--  <title><?php echo $this->translation['Application Name']; ?> | <?php echo $this->pageTitle; ?></title>-->
    <?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();
    ?>
</head>
<body class="yui-skin-sam">
<div id="pageHolder">
    <div id="header"><?php echo $header; ?></div>
    <div id="content" class="adminDiv">


        <div id="navAdmin"><?php echo $nav; ?></div>

        <div id="contentAdmin">
            <h1><?php echo t($this->pageTitle); ?></h1>

            <fieldset class="settings">
                <legend><?php echo t('Appearance'); ?></legend>
                <div class="fieldLabel"><?php echo t('Application name'); ?></div>
                <script type="text/javascript">
                    function update_app_name(newval) {
                        var app_name = YAHOO.util.Dom.get('label_application_name');
                        app_name.value = newval;
                    }
                    function confirmRegionDelete(control) {
                        if (confirm("Are you sure you want to remove this region level? All locations in this level will be erased.")) {
                            window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/delete-region";
                        }
                    }
                    function confirmRegionAddTop(control) {
                        if (confirm(tr("Are you sure you want to add a region level? A new default location will be created at this level, and all child locations will be added to this default."))) {
                            window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/add-region-top";
                        }
                    }
                    function confirmRegionAddBottom(control) {
                        if (confirm(tr("Are you sure you want to add a region level? A new default location will be created at this level, and all child locations will be added to this default."))) {
                            window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/add-region-bottom";
                        }
                    }
                </script>
                <div class="fieldInput"><input type="text" name="application_name_clone"
                                               value="<?php echo $this->translation['Application Name']; ?>"
                                               onchange="return update_app_name(this.value);" />
                </div>


            <fieldset class="settings">
                <legend><?php tp('Languages'); ?></legend>
                <br/>

                <?php foreach ($this->languages as $key => $label) { ?>
                    <div class="fieldLabel"><?php tp($label); ?></div>
                    <div class="fieldInput">
                        <input type="checkbox" name="locales[]" value="<?php echo $key; ?>"
                               id="<?php echo $key; ?>"<?php if (in_array($key, $this->locale_enabled) || $key == $this->locale) print 'checked'; ?>><label
                            for="<?php echo $key; ?>"><?php tp('Enable'); ?></label>
                        &nbsp;
                        <input type="radio" name="locale_default" value="<?php echo $key; ?>"
                               id="d<?php echo $key; ?>" <?php if ($this->locale == $key) print 'checked'; ?>><label
                            for="d<?php echo $key; ?>"><?php tp('Default'); ?></label>
                    </div>

                <?php } ?>

            </fieldset>
            <br/>


            <input type="hidden" name="redirect"
                   value="<?php echo Settings::$COUNTRY_BASE_URL . '/admin/' . $nextUri; ?>">
            <input type="submit" value="<?php tp('Save & Continue'); ?>" class="submitArrow">
            <input type="submit" value="<?php tp('Save'); ?>" name="saveonly" class="submitNoArrow"
                   style="margin-right:1em;">
            </form>


        </div>

        <div class="clear"></div>

    </div>
    <div id="footer"><?php require_once('views/scripts/footer.phtml'); ?></div>
</div>

</body>
</html>